"use client";

import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarClock, Loader2, Sparkles, Trash2, Plus } from "lucide-react";
import { saveRoutine, type RoutineState } from "../actions";
import type { Patient } from "@/core/patients/types";
import { MONITORING_ROUTINES } from "@/core/schedule/routines";
import { MONITOR_PARAMS, paramGroup, GROUP_ACCENT } from "@/core/schedule/params";
import {
  nextSlotStart,
  shiftEnd,
  generateSlots,
  tasksFromRoutine,
} from "@/core/schedule/planner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const selectClass =
  "flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

const initialState: RoutineState = {};

interface PlannedTask {
  timestamp: string; // ISO
  focus: string[];
}

function hhmm(iso: string): string {
  return new Date(iso).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
}

function horizonEnd(option: string): Date {
  const now = new Date();
  if (option === "shift") return shiftEnd(now);
  const hours = Number(option.replace("h", ""));
  return new Date(now.getTime() + hours * 60 * 60000);
}

/** Merge a list of {timestamp,focus} by exact timestamp (union of focus). */
function mergeByTime(...lists: PlannedTask[][]): PlannedTask[] {
  const map = new Map<string, Set<string>>();
  for (const list of lists) {
    for (const t of list) {
      const key = new Date(t.timestamp).toISOString();
      const set = map.get(key) ?? new Set<string>();
      t.focus.forEach((f) => set.add(f));
      map.set(key, set);
    }
  }
  return [...map.entries()]
    .map(([timestamp, set]) => ({ timestamp, focus: [...set] }))
    .filter((t) => t.focus.length > 0)
    .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
}

export function RoutinePlanner({ patient }: { patient: Patient }) {
  const [state, formAction, pending] = useActionState(saveRoutine, initialState);

  // Tasks generated by clinical routines / custom generator
  const [extraTasks, setExtraTasks] = useState<PlannedTask[]>([]);
  // Manual 15-min grid: iso -> params
  const [grid, setGrid] = useState<Record<string, string[]>>({});

  const [horizon, setHorizon] = useState("shift");
  const [customParams, setCustomParams] = useState<string[]>([]);
  const [customInterval, setCustomInterval] = useState(60);
  const [replaceFuture, setReplaceFuture] = useState(true);

  // Build the 15-min slot timeline for the manual grid
  const slots = useMemo(() => {
    const start = nextSlotStart();
    return generateSlots(start, shiftEnd(start)).map((d) => d.toISOString());
  }, []);

  const finalTasks = useMemo(() => {
    const gridTasks: PlannedTask[] = Object.entries(grid).map(([timestamp, focus]) => ({
      timestamp,
      focus,
    }));
    return mergeByTime(extraTasks, gridTasks);
  }, [extraTasks, grid]);

  function applyRoutine(routineId: string) {
    const routine = MONITORING_ROUTINES.find((r) => r.id === routineId);
    if (!routine) return;
    const start = nextSlotStart();
    const tasks = tasksFromRoutine(routine, start, horizonEnd(horizon)).map((t) => ({
      timestamp: t.timestamp,
      focus: t.focus,
    }));
    setExtraTasks((prev) => mergeByTime(prev, tasks));
  }

  function applyCustom() {
    if (customParams.length === 0) return;
    const start = nextSlotStart();
    const end = horizonEnd(horizon);
    const tasks: PlannedTask[] = [];
    for (let t = start.getTime(); t <= end.getTime(); t += customInterval * 60000) {
      tasks.push({ timestamp: new Date(t).toISOString(), focus: customParams });
    }
    setExtraTasks((prev) => mergeByTime(prev, tasks));
  }

  function toggleGrid(iso: string, param: string) {
    setGrid((prev) => {
      const cur = prev[iso] ?? [];
      const next = cur.includes(param) ? cur.filter((p) => p !== param) : [...cur, param];
      return { ...prev, [iso]: next };
    });
  }

  function toggleCustomParam(param: string) {
    setCustomParams((prev) =>
      prev.includes(param) ? prev.filter((p) => p !== param) : [...prev, param],
    );
  }

  function clearAll() {
    setExtraTasks([]);
    setGrid({});
  }

  return (
    <form action={formAction} className="space-y-5">
      <input type="hidden" name="patientId" value={patient.id} />
      <input type="hidden" name="tasks" value={JSON.stringify(finalTasks)} />
      {replaceFuture && <input type="hidden" name="replaceFuture" value="on" />}

      {/* Horizonte */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Horizonte do planejamento</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap items-center gap-3">
            <select
              value={horizon}
              onChange={(e) => setHorizon(e.target.value)}
              className={`${selectClass} w-auto`}
            >
              <option value="shift">Até o fim do plantão</option>
              <option value="6h">Próximas 6 horas</option>
              <option value="12h">Próximas 12 horas</option>
              <option value="24h">Próximas 24 horas</option>
            </select>
            <p className="text-xs text-muted-foreground">
              As rotinas e o gerador criam aferições a partir de agora até esse limite.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Rotinas clínicas */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Sparkles className="h-4 w-4 text-primary" /> Rotinas clínicas
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {MONITORING_ROUTINES.map((r) => (
            <div key={r.id} className="rounded-lg border p-3">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-semibold">{r.label}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{r.description}</p>
                </div>
                <Button type="button" size="sm" variant="outline" onClick={() => applyRoutine(r.id)}>
                  <Plus className="h-4 w-4" /> Aplicar
                </Button>
              </div>
              <div className="mt-2 flex flex-wrap gap-1">
                {r.rules.map((rule, i) => (
                  <span
                    key={i}
                    className="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground"
                  >
                    {rule.params.join("+")} · {rule.intervalMin}min
                  </span>
                ))}
              </div>
              <details className="mt-2">
                <summary className="cursor-pointer text-[11px] text-muted-foreground">
                  Referências
                </summary>
                <ul className="mt-1 list-disc pl-4 text-[11px] text-muted-foreground">
                  {r.references.map((ref) => (
                    <li key={ref}>{ref}</li>
                  ))}
                </ul>
              </details>
            </div>
          ))}
          <p className="rounded-md bg-amber-50 px-3 py-2 text-xs text-amber-800">
            ⚠️ Intervalos sugeridos para apoio à decisão (gestação de baixo risco / protocolos
            padrão). Ajuste conforme o quadro e valide com a equipe.
          </p>
        </CardContent>
      </Card>

      {/* Gerador personalizado */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Gerador personalizado</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex flex-wrap gap-1.5">
            {MONITOR_PARAMS.map((p) => {
              const active = customParams.includes(p.id);
              return (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => toggleCustomParam(p.id)}
                  className={`rounded-md border px-2.5 py-1 text-xs font-medium transition-colors ${
                    active ? GROUP_ACCENT[p.group] : "bg-background text-muted-foreground"
                  }`}
                >
                  {p.label}
                </button>
              );
            })}
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <select
              value={customInterval}
              onChange={(e) => setCustomInterval(Number(e.target.value))}
              className={`${selectClass} w-auto`}
            >
              <option value={15}>A cada 15 min</option>
              <option value={30}>A cada 30 min</option>
              <option value={60}>A cada 1 hora</option>
              <option value={120}>A cada 2 horas</option>
              <option value={180}>A cada 3 horas</option>
              <option value={240}>A cada 4 horas</option>
              <option value={360}>A cada 6 horas</option>
            </select>
            <Button type="button" size="sm" variant="outline" onClick={applyCustom}>
              <Plus className="h-4 w-4" /> Aplicar
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Grade manual */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Ajuste manual (grade de 15 min)</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="max-h-[50vh] overflow-y-auto rounded-md border">
            {slots.map((iso) => {
              const sel = grid[iso] ?? [];
              const has = sel.length > 0;
              return (
                <div
                  key={iso}
                  className={`grid grid-cols-[56px_1fr] border-b last:border-0 ${
                    has ? "bg-primary/5" : ""
                  }`}
                >
                  <div
                    className={`flex items-center justify-center border-r text-xs font-bold ${
                      has ? "text-primary" : "text-muted-foreground"
                    }`}
                  >
                    {hhmm(iso)}
                  </div>
                  <div className="grid grid-cols-6 gap-1 p-1.5">
                    {MONITOR_PARAMS.map((p) => {
                      const active = sel.includes(p.id);
                      return (
                        <button
                          key={p.id}
                          type="button"
                          onClick={() => toggleGrid(iso, p.id)}
                          className={`h-7 rounded text-[10px] font-bold transition-colors ${
                            active
                              ? GROUP_ACCENT[paramGroup(p.id)]
                              : "border bg-background text-muted-foreground"
                          }`}
                        >
                          {p.label}
                        </button>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Resumo */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between text-base">
            <span>Resumo — {finalTasks.length} aferições</span>
            {finalTasks.length > 0 && (
              <Button type="button" size="sm" variant="ghost" className="text-destructive" onClick={clearAll}>
                <Trash2 className="h-4 w-4" /> Limpar
              </Button>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {finalTasks.length > 0 ? (
            <ul className="space-y-1 text-sm">
              {finalTasks.slice(0, 8).map((t) => (
                <li key={t.timestamp} className="flex items-center gap-2">
                  <span className="font-mono font-bold">{hhmm(t.timestamp)}</span>
                  <span className="flex flex-wrap gap-1">
                    {t.focus.map((f) => (
                      <span
                        key={f}
                        className={`rounded border px-1.5 py-0.5 text-[10px] font-medium ${GROUP_ACCENT[paramGroup(f)]}`}
                      >
                        {f}
                      </span>
                    ))}
                  </span>
                </li>
              ))}
              {finalTasks.length > 8 && (
                <li className="text-xs text-muted-foreground">
                  + {finalTasks.length - 8} aferições…
                </li>
              )}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">
              Nenhuma aferição planejada ainda. Aplique uma rotina ou marque horários na grade.
            </p>
          )}

          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={replaceFuture}
              onChange={(e) => setReplaceFuture(e.target.checked)}
              className="h-4 w-4 rounded border-input"
            />
            Substituir rotina futura pendente existente
          </label>

          {state.error && (
            <p className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">
              {state.error}
            </p>
          )}

          <div className="flex justify-end gap-2">
            <Link
              href={`/pre-parto/${patient.id}`}
              className="self-center text-sm text-muted-foreground hover:text-foreground"
            >
              Cancelar
            </Link>
            <Button type="submit" disabled={pending || finalTasks.length === 0}>
              {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <CalendarClock className="h-4 w-4" />}
              Salvar rotina
            </Button>
          </div>
        </CardContent>
      </Card>
    </form>
  );
}
